version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fraudshield-sqlserver
    environment:
      SA_PASSWORD: "fraudshield@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: fraudshield-rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  # redis:
  #   image: redis:alpine
  #   container_name: fraudshield-redis
  #   ports:
  #     - "6379:6379"

volumes:
  sqlserver_data:
